apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJ5b25hdGFuZ29saWNrIiwicGFzc3dvcmQiOiJZb25uaTE5OTYiLCJhdXRoIjoiZVc5dVlYUmhibWR2YkdsamF6cFpiMjV1YVRFNU9UWT0ifX19
kind: Secret
metadata:
  name: regcred
  namespace: default
type: kubernetes.io/dockerconfigjson
